apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Java-goof
  description: Java Goof
  annotations:
    snyk.io/org-name: aarlaud-snyk-demo
    snyk.io/project-id-1: b17b47c4-8013-42ae-a9d1-12c48d1ee864
    snyk.io/project-id-2: 34dd9984-1925-4cb9-8abf-b47b1fb25534
    snyk.io/project-id-3: 5dc68982-7a59-4ab1-82a8-4f0b29a6e512
spec:
  type: service
  lifecycle: production
  owner: guest

